spring.datasource.url=jdbc:h2:mem:produits-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# Evite de re-générer le login par défaut de Spring Boot (mot de passe aléatoire en console)
# puisqu'on utilise notre propre UserDetailsService + page de login personnalisée.
